DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/mnt/../code/stitchfusion/checkpoints_training/stitchfusion_fmb'          # output folder name used for saving the model, logs and inference results
GPUs            : 4
GPU_IDs         : [0, 1, 2, 3]
USE_WANDB       : False
WANDB_NAME      : 'stitchfusion-FMB-RGBT'             # name for the run

MODEL:
  NAME          : stitchfusion                                         # name of the model you are using
  BACKBONE      : stitchfusion-B3                                      # model variant
  PRETRAINED    : '/mnt/../code/stitchfusion/checkpoints/pretrained/segformers/mit_b3.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : FMB                                               # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/mnt/../code/stitchfusion/data/FMB'                            # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['img']
  MODALS        : ['img', 'thermal'] 

TRAIN:
  IMAGE_SIZE    : [800, 600]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 12               # batch size used to train
  EPOCHS        : 120             # number of epochs to train
  EVAL_START    : 20               # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : true            # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00012         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : ''                 # Path to your saved model
  IMAGE_SIZE    : [800, 600]                              # evaluation image size in (h, w)                       
  BATCH_SIZE    : 12                                       # batch size
  BATCH_SIZE_VIS    : 1                                       # batch size
  VIS_SAVE_DIR  : '/mnt/../code/stitchfusion/checkpoints_vis/stitchfusion_fmb/RGB'              # Where to save visualization
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
  OVERLAY       : false                                   # save the overlay result (image_alpha+label_alpha)